name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

            # Check if version has changed
      - name: Check version changes
        id: check
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "none")
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [ "$LATEST_TAG" = "v$PACKAGE_VERSION" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v2
        if: steps.check.outputs.skip == 'false'
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        if: steps.check.outputs.skip == 'false'
        run: npm install

      - name: Copy file to cli
        if: steps.check.outputs.skip == 'false'
        run: npm run copy-cli

      - name: Deploy to cli
        if: steps.check.outputs.skip == 'false'
        run: npm run deploy-cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Storybook
        if: steps.check.outputs.skip == 'false'
        run: npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: steps.check.outputs.skip == 'false'
        with:
          branch: gh-pages
          folder: storybook-static
